Repository starter-code/res-gen, pull requests merged in 2020-10, with the labels that each got.

#9 chore(react-pdf): update packages and webpack
  .eslintignore
  .eslintrc.json
  .prettierignore
  .prettierrc
  .vscode/settings.json
  README.md
  package-lock.json
  package.json
  src/components/app/App.js
  src/components/routes/Routes.js
  src/example-json/john_smith.json
  src/index.js
  src/scss/Pdf.scss
  src/scss/index.scss
  webpack.config.js
Labels: chore

#11 chore(roadmap): update v0.1.0
  documentation/backlog.md
  documentation/roadmap.md
Labels: documentation, ready for review

#16 chore(github): add pr template
  .github/pull_request_template.md
Labels: chore

#17 chore(fonts): split font loading into fonts.js
  src/fonts/fonts.js
  src/index.js
Labels: chore

#18 refactor(templates): add HOC base template
  documentation/backlog.md
  documentation/roadmap.md
  documentation/techdebt.md
  example-pdfs/Foles.png
  example-pdfs/Mahomes.png
  src/components/pages/CrispPage.js
  src/components/pages/FolesPage.js
  src/components/pages/MahomesPage.js
  src/components/pages/index.js
  src/components/templates/BaseTemplate/BaseTemplate.js
  src/components/templates/Crisp.js
  src/components/templates/FolesTemplate/FolesTemplate.js
  src/components/templates/FolesTemplate/index.js
  src/components/templates/MahomesTemplate/ContentColumn.js
  src/components/templates/MahomesTemplate/InfoColumn.js
  src/components/templates/MahomesTemplate/MahomesTemplate.js
  src/components/templates/MahomesTemplate/index.js
  src/example-json/john_smith.json
Labels: refactor
